# pull official base image
FROM node:14-alpine

RUN apk add openjdk11

RUN npm install -g firebase-tools

WORKDIR /app

# start db in emulator
CMD ["firebase", "--project=web-queue", "emulators:start", "--only", "firestore"]