version: '3.8'
services:
  web-queue:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web-queue
#    depends_on:
#      - db
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src:/src
#Todo: Figure out how to setup local firebase emulator setup with docker-compose
#  db:
#    image: firestore
#    build:
#      context: web-queue
#      dockerfile: Dockerfile.firestore
#    ports:
#      - 4000:4000
#      - 8080:8080
#    volumes:
#      - .cache/firebase/emulators/:/app/.cache/firebase/emulators/